# Generated by Django 3.1.4 on 2021-04-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='questions_base',
            fields=[
                ('sl_no', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(default='', max_length=500)),
                ('option1', models.CharField(default='', max_length=100)),
                ('option2', models.CharField(default='', max_length=100)),
                ('option3', models.CharField(default='', max_length=100)),
                ('option4', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
