# Generated by Django 3.1.4 on 2021-03-01 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210301_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='main_id',
        ),
    ]
