# Generated by Django 3.1.4 on 2021-02-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recieve_content',
            old_name='f_name',
            new_name='fname',
        ),
        migrations.RenameField(
            model_name='recieve_content',
            old_name='l_name',
            new_name='lname',
        ),
    ]
