# Generated by Django 3.1.4 on 2021-02-25 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210225_1430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recieve_content',
            old_name='fname',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='recieve_content',
            old_name='lname',
            new_name='name',
        ),
    ]
