# Generated by Django 3.1.4 on 2021-03-02 18:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210225_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recieve_content',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
